config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"

  root "homes#top"
  get "homes/about" => "homes#about"
  get 'tops/trend' => "tops#index"
  get 'tops/favorite' => "tops#favorite"
  post 'homes/guest_sign_in' => "homes#new_guest"
  devise_for :users, controller: {
    sessions: "users/sessions",
    registrations: "users/registrations",
  }
  
  resources :users, only: [:index, :edit, :show, :update, :destroy, :create] do
    resource :frendships, only: [:create, :destroy]
    resources :rooms, only: [:show, :create, :new]
    get "user_top" => "users#top", as: "top"
    get "user_favorites" => "users#favorite", as: "favorites"
    get :follows, on: :member
    get :followers, on: :member
    get "confirm" => "users#confirm", as: "confirm"
    get "follower" => "frendships#follower", as: "follower"
    get "following" => "frendships#following", as: "following"
    get "user_index" => "emotions#user_index", as: "emotion_index"
    get "user_gourmet_index" => "gourmets#user_gourmet_index", as: "gourmets_index"
  end

  resources :emotions, only: [:show, :create, :new] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:index, :create, :destroy]
  end

  resources :gourmets, only: [:show, :create, :new] 

  get "search" => "search#search", as: "search"
  get "user_search" => "search#user_search", as: "user_search"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :emotion
  belongs_to :user

  validates :body, presence: true, length: { maximum: 50 }
end

app/models/emotion.rb
class Emotion < ApplicationRecord
  acts_as_taggable

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  accepts_attachments_for :images, attachment: :image

  validates :body, presence: true, length: { maximum: 140 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :emotion
end

app/models/frendship.rb
class Frendship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/gourmet.rb
class Gourmet < ApplicationRecord
    acts_as_taggable
    belongs_to :user
    validates :body, presence: true, length: { maximum: 140 }
    has_many :gourmet_images, dependent: :destroy
    accepts_attachments_for :gourmet_images, attachment: :image
end

app/models/gourmet_image.rb
class GourmetImage < ApplicationRecord
    belongs_to :gourmet
    attachment :image
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :emotion
  attachment :image
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :texts
    belongs_to :user

    validates :room_name, presence: true
end

app/models/text.rb
class Text < ApplicationRecord
    after_create_commit { MessageBroadcastJob.perform_later self }
    # belongs_to :user
    # belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid
  acts_as_taggable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :emotions, dependent: :destroy
  has_many :gourmets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :profile_image
  attachment :header_image
  has_many :active_relationships, class_name: "Frendship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Frendship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  has_many :texts
  has_many :rooms

  validates :name, presence: true, length: { maximum: 20 }
  validates :introduction, presence: false, on: :update, length: { maximum: 50 }

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  enum favorite_team: {
    未選択: 0, 東京ヤクルトスワローズ: 1, 読売ジャイアンツ: 2, 阪神タイガース: 3, 広島東洋カープ: 4, 横浜DeNAベーイスターズ: 5, 中日ドラゴンズ: 6,
    福岡ソフトバンク: 7, 埼玉西武ライオンズ: 8, 千葉ロッテマリンズ: 9, 東北楽天ゴールデンイーグルス: 10, オリックスバッファローズ: 11, 北海道日本ハムファイターズ: 12,
  }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def top
    @user = User.find(params[:user_id])
    @emotions = @user.emotions.page(params[:page]).order(created_at: :desc)
    @gourmets = @user.gourmets.page(params[:page]).order(created_at: :desc)
  end

  def index
    if params[:tag_name]
      @users = User.tagged_with("#{params[:tag_name]}")
    end
  end

  def favorite
    @user = User.find_by(id: params[:user_id])
    @favorites = @user.favorites.all
  end

  def show
    @user = User.find(params[:id])
    @emotions = @user.emotions.page(params[:page]).order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to root_path
    end
  end

  def confirm
    @users = User.all.sample(3)
  end

  def destroy
    @user = current_user
    if @user.email == "guest02@example.com"
      flash[:notice] = "ゲストユーザーは退会できません"
      redirect_to user_top_path(@user)
    else
      @user.destroy
      flash[:notice] = "退会が完了しました。"
      redirect_to root_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "編集が完了しました。"
      redirect_to user_top_path(current_user)
    else
      render "edit"
    end
  end

  def create
    @texts = Text.new(params[message])
    @texts.save
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :favorite_team, :textbox, :tag_list, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_top_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/emotions_helper.rb
module EmotionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/frends_helper.rb
module FrendsHelper
end

app/helpers/gourmets_helper.rb
module GourmetsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/confirm.html.erb
<div class="confirm">
  <%= link_to "本当に退会する", user_path(current_user), class: "btn-primary", method: :delete %>
</div>
<h5>こんなユーザーがいます</h5>
<div class="user-search">
<% @users.each do |user| %>
  <div class="demo-card-square mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title mdl-card--expand">
    <%= link_to user_top_path(user) do %>
    <section>
    <% if user.profile_image.present? %>
        <%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "100x100", class: "img" %>
    <% else %>
        <%= image_tag "no_image.jpg", format: 'jpeg', size: "100x100", class: "img" %>
    <% end %>
    </section>
    <section>
      <h1 class="mdl-card__title-text">
      <%= user.name %>
      </h1>
      </section>
    <% end %>
    </div>
    <div class="mdl-card__supporting-text">
      <h3 class="mdl-card__title-text">
        <%= link_to user_follower_path(user) do %>
        Follower数　<%=user.followers.count %>　<br>
        <% end %>
        <%= link_to user_following_path(user) do %>
        Folloing数　<%=user.followings.count %>　<br>
        <% end %>
        <%= link_to user_favorites_path(user) do %>
        Favorite数　<%=user.favorites.count %><br>
        <% end %>
      </h3> 
    </div>
    <div class="mdl-card__actions mdl-card--border">
        <h5>紹介文</h5>
          <span><%= user.introduction %><br></span>
        <h5>お気に入りの球団</h5>
          <span><%= user.favorite_team %></span>
        <% if current_user.id != user.id %>
          <% if user.followed_by?(current_user) %>
            <p><%= link_to "フォロー解除", user_frendships_path(user), method: :delete %></p>
          <% else %>
            <p><%= link_to "フォロー登録", user_frendships_path(user), method: :post %></p></p>
          <% end %>    
        <% end %>  
    </div>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<div class="user-info edit">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
      <div class="notice">
              <p><%= @user.errors.count %>件エラーがあります。</p>
              <% @user.errors.full_messages.each do |message| %>
              <ul>
                  <li><%= message %></li>
              </ul>
              <% end %>
      </div>
  <% end %>
  <section>
    <% if @user.header_image.present? %>
      <%= attachment_image_tag @user, :header_image, format: 'jpeg', size: "100x100", class: "header-img" %><br>
    <% else %>
      <%= image_tag "top1.jpg", format: 'jpeg', size: "100x100", class: "header-img" %><br>
    <% end %>
    <%= f.attachment_field :header_image, placeholder: "ヘッダー画像"%>
  </section>
<div class="demo-card-square mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title mdl-card--expand">
  <section>
    <% if @user.profile_image.present? %>
      <%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "100x100", class: "img" %><br>
    <% else %>
      <%= image_tag "no_image.jpg", format: 'jpeg', size: "100x100", class: "img" %><br>
    <% end %>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像"%>
  </section>
  <section>
  </section>
  </div>
  <div class="mdl-card__supporting-text">
  </div>
  <div class="mdl-card__actions mdl-card--border">
    <h5>ユーザー名</h5>
    <span><%= f.text_field :name %></span>
    <h5>紹介文</h5>
    <span><%= f.text_area :introduction %></span>
    <h5>お気に入りの球団</h5>
    <span><%= f.select :favorite_team, User.favorite_teams.keys,{} %></span>
    <h5>野球との出会いは？？</h5>
    <span><%= f.text_field :textbox %></span>
    <h5>タグ</h5>
    <span>
    <%= f.text_field :tag_list, value: @user.tag_list.join(',') %>  
    </span>
    <%= f.submit "変更を確定する", class: "btn btn-primary" %>
    <%= link_to "退会手続きをする", user_confirm_path(current_user) %>
  </div>
</div>
<% end %>
</div>

app/views/users/favorite.html.erb
<div class="index-book">
<h5>お気に入りの投稿一覧</h5>
<% @favorites.each do |favorite| %>
    <% if favorite.emotion&.score > 0.3 %>
    <div class= "demo-card-wide mdl-card mdl-shadow--2dp score-color1">
    <% elsif favorite.emotion&.score > -0.6 %>
    <div class= "demo-card-wide mdl-card mdl-shadow--2dp score-color2">
    <% else %> 
    <div class= "demo-card-wide mdl-card mdl-shadow--2dp score-color3">
    <% end %>
    <div class="mdl-card__supporting-text">
      <section>
        <%= link_to user_top_path(favorite.emotion.user) do %>
          <% if favorite.emotion.user.profile_image.present? %>
            <p><%= attachment_image_tag favorite.emotion.user, :profile_image, format: 'jpeg', size: "100x100", class: "img" %></p>
          <% else %>
            <p><%= image_tag "no_image.jpg", format: 'jpeg', size: "100x100", class: "img" %></p>
          <% end %>
          ユーザー名　<%= favorite.emotion.user.name %>　
        <% end %>
          <%= time_ago_in_words(favorite.emotion.created_at) %>前
            　コメント数　<%= favorite.emotion.comments.count %> 件
            　投稿画像　<%= favorite.emotion.images.count %> 件<br>
          <p id="favorite_<%= favorite.emotion.id %>">
          <%= render "forms/favorite", emotion: favorite.emotion %>
          </p> 
        </section>
    </div>
    <div class="mdl-card__actions mdl-card--border">
        <%= link_to emotion_path(favorite.emotion) do %>
          <%= favorite.emotion.body %>
        <% end %>
    </div>
  </div>
<% end %>
</div>

app/views/users/index.html.erb
<% @users.each do |data| %>
<div class="user-search">
<div class="demo-card-square mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title mdl-card--expand">
  <%= link_to user_top_path(data) do %>
  <section>
  <% if data.profile_image.present? %>
      <%= attachment_image_tag data, :profile_image, format: 'jpeg', size: "100x100", class: "img" %>
  <% else %>
      <%= image_tag "no_image.jpg", format: 'jpeg', size: "100x100", class: "img" %>
  <% end %>
  </section>
  <section>
    <h1 class="mdl-card__title-text">
    <%= data.name %>
    </h1>
    </section>
  <% end %>
  </div>
  <div class="mdl-card__supporting-text">
    <h3 class="mdl-card__title-text">
      <%= link_to user_follower_path(data) do %>
      Follower数　<%=data.followers.count %>　<br>
      <% end %>
      <%= link_to user_following_path(data) do %>
      Folloing数　<%=data.followings.count %>　<br>
      <% end %>
      <%= link_to user_favorites_path(data) do %>
      Favorite数　<%=data.favorites.count %><br>
      <% end %>
    </h3> 
  </div>
  <div class="mdl-card__actions mdl-card--border">
      <h5>紹介文</h5>
        <span><%= data.introduction %><br></span>
      <h5>お気に入りの球団</h5>
        <span><%= data.favorite_team %></span>
      <% if current_user.id != data.id %>
        <% if data.followed_by?(current_user) %>
          <p><%= link_to "フォロー解除", user_frendships_path(data), method: :delete %></p>
        <% else %>
          <p><%= link_to "フォロー登録", user_frendships_path(data), method: :post %></p></p>
        <% end %>    
      <% end %>  
  </div>
</div>
</div>
<% end %>

app/views/users/show.html.erb
<div class="user-info">
<div class="demo-card-square mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title mdl-card--expand">
  <%= link_to user_top_path(@user) do %>
  <section>
  <% if @user.profile_image.present? %>
      <%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "100x100", class: "img" %>
  <% else %>
      <%= image_tag "no_image.jpg", format: 'jpeg', size: "100x100", class: "img" %>
  <% end %>
  </section>
  <section>
    <h1 class="mdl-card__title-text">
    <%= @user.name %>
    </h1>
    </section>
  <% end %>
  </div>
  <div class="mdl-card__supporting-text">
    <h3 class="mdl-card__title-text">
      <%= link_to user_follower_path(@user) do %>
      Follower数　<%=@user.followers.count %>　<br>
      <% end %>
      <%= link_to user_following_path(@user) do %>
      Folloing数　<%=@user.followings.count %>　<br>
      <% end %>
      <%= link_to user_favorites_path(@user) do %>
      Favorite数　<%=@user.favorites.count %><br>
      <% end %>
    </h3> 
  </div>
  <div class="mdl-card__actions mdl-card--border">
      <h5>紹介文</h5>
        <span><%= @user.introduction %><br></span>
      <h5>お気に入りの球団</h5>
        <span><%= @user.favorite_team %></span>
      <h5>野球と出会ったきっかけ</h5>
        <span><%= @user.textbox %><br></span>
      <h5>登録しているタグ</h5>
      <span>
          <% @user.tag_list.each do |tag| %>
          <%= link_to tag, users_path(tag_name: tag) %>
        <% end %>　
      </span>  
      <% if current_user.id != @user.id %>
        <% if @user.followed_by?(current_user) %>
          <p><%= link_to "フォロー解除", user_frendships_path(@user), method: :delete %></p>
        <% else %>
          <p><%= link_to "フォロー登録", user_frendships_path(@user), method: :post %></p></p>
        <% end %>    
      <% end %>  
  </div>
</div>
</div>

app/views/users/top.html.erb
<% if @user == current_user %>
  <% if current_user.introduction.blank? %>
  <div id="mask">
  </div>
      <div id="introduction-confirm">
        <h5>まずは自分のことを知ってもらおう！</h5>
        <% if @user.profile_image.present? %>
          <%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "100x100", class: "img" %>
        <% else %>
          <%= image_tag "no_image.jpg", format: 'jpeg', size: "100x100", class: "img" %>
        <% end %>
        <span><%= link_to "早速プロフィールを設定する", edit_user_path(@user) %></span>
        <a id="edit-after">あとにする</a>
      </div>
  <% end %>
<% end %>
<div class="header-img">
<% if @user.header_image.present? %>
      <%= attachment_image_tag @user, :header_image, format: 'jpeg', class: "header-img" %>
<% else %>
      <%= image_tag "top1.jpg", format: 'jpeg', class: "header-img" %>
<% end %>
</div>
<div class="flex">
  <%= render "forms/user" %>
  <div class="book">
    <div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
      <div class="mdl-tabs__tab-bar">
          <a href="#starks-panel" class="mdl-tabs__tab is-active">Baseball(<%= @emotions.count %>)</a>
          <a href="#lannisters-panel" class="mdl-tabs__tab">Gourmet(<%= @gourmets.count %>)</a>
      </div>
      <div class="mdl-tabs__panel is-active" id="starks-panel">
          <% if @emotions.present? %>
            <% @emotions.each do |emotion| %>
              <% if emotion&.score > 0.3 %>
              <div class= "demo-card-wide mdl-card mdl-shadow--2dp score-color1">
              <% elsif emotion&.score > -0.6 %>
              <div class= "demo-card-wide mdl-card mdl-shadow--2dp score-color2">
              <% else %> 
              <div class= "demo-card-wide mdl-card mdl-shadow--2dp score-color3">
              <% end %>
                <div class="mdl-card__supporting-text">
                  <section>
                      <%= time_ago_in_words(emotion.created_at) %>前
                        　コメント数　<%= emotion.comments.count %> 件
                        　投稿画像　<%= emotion.images.count %> 件<br>
                      <p id="favorite_<%= emotion.id %>">
                      <%= render "forms/favorite", emotion: emotion %>
                      </p> 
                    </section>
                </div>
                <div class="mdl-card__actions mdl-card--border">
                    <%= link_to emotion_path(emotion) do %>
                      <%= emotion.body %>
                    <% end %>
                </div>
              </div>
            <% end %>
            <%= paginate @emotions %>
          <% else %>
          <p>投稿がまだありません</p>
          <% end %>      
      </div>
      <div class="mdl-tabs__panel" id="lannisters-panel">
            <% if @gourmets.present? %>
            <% @gourmets.each do |gourmet| %>
              <div class= "demo-card-wide mdl-card mdl-shadow--2dp">
                <div class="mdl-card__supporting-text">
                  <section>
                      <%= time_ago_in_words(gourmet.created_at) %>前
                      投稿画像　<%= gourmet.gourmet_images.count %> 件<br>
                      <% unless gourmet.rate == nil %>
                        <div id="star-rate-<%= gourmet.id %>"></div>
                          <script>
                          $('#star-rate-<%= gourmet.id %>').raty({
                            size: 36,
                            starOff:  '<%= asset_path('star-off.png') %>',
                            starOn : '<%= asset_path('star-on.png') %>',
                            starHalf: '<%= asset_path('star-half.png') %>',
                            half: true,
                            readOnly: true,
                            score: <%= gourmet.rate %>,
                          });
                          </script> 
                      <% end %>   
                    </section>
                </div>
                <div class="mdl-card__actions mdl-card--border">
                    <%= link_to gourmet_path(gourmet) do %>
                      <%= gourmet.body %>
                    <% end %>
                </div>
              </div>
            <% end %>
            <%= paginate @gourmets %>
            <% else %>
            <p>投稿がまだありません</p>
            <% end %> 
      </div>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>