config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"

  root "homes#top"
  get "homes/about" => "homes#about"
  get 'tops/trend' => "tops#index"
  get 'tops/favorite' => "tops#favorite"
  post 'homes/guest_sign_in' => "homes#new_guest"
  devise_for :users, controller: {
    sessions: "users/sessions",
    registrations: "users/registrations",
  }
  
  resources :users, only: [:index, :edit, :show, :update, :destroy, :create] do
    resource :frendships, only: [:create, :destroy]
    resources :rooms, only: [:show, :create, :new]
    get "user_top" => "users#top", as: "top"
    get "user_favorites" => "users#favorite", as: "favorites"
    get :follows, on: :member
    get :followers, on: :member
    get "confirm" => "users#confirm", as: "confirm"
    get "follower" => "frendships#follower", as: "follower"
    get "following" => "frendships#following", as: "following"
    get "user_index" => "emotions#user_index", as: "emotion_index"
    get "user_gourmet_index" => "gourmets#user_gourmet_index", as: "gourmets_index"
  end

  resources :emotions, only: [:show, :create, :new] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:index, :create, :destroy]
  end

  resources :gourmets, only: [:show, :create, :new] 

  get "search" => "search#search", as: "search"
  get "user_search" => "search#user_search", as: "user_search"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :emotion
  belongs_to :user

  validates :body, presence: true, length: { maximum: 50 }
end

app/models/emotion.rb
class Emotion < ApplicationRecord
  acts_as_taggable

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  accepts_attachments_for :images, attachment: :image

  validates :body, presence: true, length: { maximum: 140 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :emotion
end

app/models/frendship.rb
class Frendship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/gourmet.rb
class Gourmet < ApplicationRecord
    acts_as_taggable
    belongs_to :user
    validates :body, presence: true, length: { maximum: 140 }
    has_many :gourmet_images, dependent: :destroy
    accepts_attachments_for :gourmet_images, attachment: :image
end

app/models/gourmet_image.rb
class GourmetImage < ApplicationRecord
    belongs_to :gourmet
    attachment :image
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :emotion
  attachment :image
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :texts
    belongs_to :user

    validates :room_name, presence: true
end

app/models/text.rb
class Text < ApplicationRecord
    after_create_commit { MessageBroadcastJob.perform_later self }
    # belongs_to :user
    # belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid
  acts_as_taggable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :emotions, dependent: :destroy
  has_many :gourmets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :profile_image
  attachment :header_image
  has_many :active_relationships, class_name: "Frendship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Frendship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  has_many :texts
  has_many :rooms

  validates :name, presence: true, length: { maximum: 20 }
  validates :introduction, presence: false, on: :update, length: { maximum: 50 }

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  enum favorite_team: {
    未選択: 0, 東京ヤクルトスワローズ: 1, 読売ジャイアンツ: 2, 阪神タイガース: 3, 広島東洋カープ: 4, 横浜DeNAベーイスターズ: 5, 中日ドラゴンズ: 6,
    福岡ソフトバンク: 7, 埼玉西武ライオンズ: 8, 千葉ロッテマリンズ: 9, 東北楽天ゴールデンイーグルス: 10, オリックスバッファローズ: 11, 北海道日本ハムファイターズ: 12,
  }
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/emotions_helper.rb
module EmotionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/frends_helper.rb
module FrendsHelper
end

app/helpers/gourmets_helper.rb
module GourmetsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forms/_favorite.html.erb
<% if emotion.favorited_by?(current_user) %>
        <%= link_to emotion_favorites_path(emotion), method: :delete, remote: true do %>
            <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
            いいね数　<%= emotion.favorites.count %> 
          <% end %>
<% else %>
        <%= link_to emotion_favorites_path(emotion), method: :post, remote: true do %>
          <i class="fa fa-heart-o" aria-hidden="true"></i>
          いいね数　<%= emotion.favorites.count %> 
        <% end %>
<% end %>

app/views/forms/_flash.html.erb
<div id="flash" class="alert-info">
    <%= flash[:notice] %>
</div>

app/views/forms/_footer.html.erb
<p>Copyright © yuya.sato All Rights Reserved.</p>
 <nav>
    <%# <li>
        <ul>お問い合わせはこちらから</ul>
    </li> %>
 </nav>

app/views/forms/_header.html.erb
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
    <span class="mdl-layout-title">
  <% unless user_signed_in? %>
    <%= link_to root_path do %>
      <div><%= image_tag "logo.jpg", format: 'jpeg', class: "logo" %></div>
    <% end %>
  <% else %>
    <%= link_to tops_trend_path, data: {"turbolinks"=>false} do %>
      <div><%= image_tag "logo.jpg", format: 'jpeg', class: "logo" %></a></div>
    <% end %>
  <% end %>
    </span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation. We hide it in small screens. -->
      <nav class="mdl-navigation mdl-layout--large-screen-only">
      <% if user_signed_in? %>
      <a class="mdl-navigation__link"><%= link_to "最近の投稿をみる", tops_trend_path %></a>
      <a class="mdl-navigation__link"><%= link_to "野球投稿をする", new_emotion_path, class: "top-btn" %></a>
      <a class="mdl-navigation__link"><%= link_to "グルメ投稿をする", new_gourmet_path, class: "top-btn" %></a>
      <% else %>  
      <a class="mdl-navigation__link"><%= link_to "ログインする", new_user_session_path, class: "home-top-btn" %></a>
      <a class="mdl-navigation__link"><%= link_to "新規登録する", new_user_registration_path, class: "home-top-btn" %></a>
      <a class="mdl-navigation__link"><%= link_to "簡単ログイン（ゲストログイン）", homes_guest_sign_in_path, method: :post, class: "home-top-btn" %></a>
      </nav>
      <% end %>
      </nav>
    </div>
  </header>
  <div class="mdl-layout__drawer">
  <% if user_signed_in? %>
    <span class="mdl-layout-title">MENU</span>
    <nav class="mdl-navigation">
      <p class="mdl-navigation__link">
      <%= link_to user_top_path(current_user) do %>
      <% if current_user.profile_image.present? %>
        <%= attachment_image_tag current_user, :profile_image, format: 'jpeg', size: "100x100", class: "img" %>
      <% else %>
        <%= image_tag "no_image.jpg", format: 'jpeg', size: "100x100", class: "img" %>
      <% end %> 
      <%= current_user.name %>
      <% end %>
      </p>
      <p class="mdl-navigation__link">
        <%= link_to "マイページにいく", user_top_path(current_user) %>
      </p>
      <p class="mdl-navigation__link">
        <%= link_to "最近の投稿みる", tops_trend_path %>
      </p>
      <p class="mdl-navigation__link">
        <%= link_to "野球投稿をする", new_emotion_path, class: "media-new" %>
      </p>
      <p class="mdl-navigation__link">
       <%= link_to "グルメ投稿をする", new_gourmet_path %></a>
      </p>
      <p class="mdl-navigation__link">
        <%= link_to "友達を探す", user_search_path(current_user) %>
      </p>
      <p class="mdl-navigation__link">
        <%= link_to "設定変更", edit_user_path(current_user) %>
      </p>
      <p class="mdl-navigation__link">
        <%= link_to "ログアウトする", destroy_user_session_path, method: :delete %> 
      </p>
    </nav>
  <% else %>
    <nav class="mdl-navigation">
      <p class="mdl-navigation__link"><%= link_to "当サイトについて", homes_about_path %></p>
      <p class="mdl-navigation__link"><%= link_to "ログインする", new_user_session_path %></p>
      <p class="mdl-navigation__link"><%= link_to "新規登録する", new_user_registration_path %></p>
      <p class="mdl-navigation__link"><%= link_to "簡単ログイン（ゲストログイン）", homes_guest_sign_in_path, method: :post %></p>
      <a class="mdl-navigation__link" href=""></a>
      <a class="mdl-navigation__link" href=""></a>
      <a class="mdl-navigation__link" href=""></a>
    </nav>
  <% end %>
  </div>
</div>
 

app/views/forms/_left_sidebar.html.erb
<p><%= link_to "最近の投稿", tops_trend_path %></p>
<p>トレンド記事</p>
<p>お気に入りの球団の投稿</p>

app/views/forms/_message.html.erb
<div class="message">
    <p><%= "#{message.user.name}: #{message.text}" %></p>
</div>

app/views/forms/_right_sidebar.html.erb
<% if current_user.profile_image.present? %>
    <%= attachment_image_tag current_user, :profile_image, format: 'jpeg', size: "100x100", class: "img" %>
   <% else %>
    <%= image_tag "no_image.jpg", format: 'jpeg', size: "100x100", class: "img" %>
   <% end %> 
   ユーザ名：<%= current_user.name %></p>
<%= link_to "新規投稿", new_emotion_path, class: "media-new" %>
<%= link_to "マイページにいく", user_top_path(current_user) %>
<%= link_to "最近の投稿", tops_trend_path %></p>
<%= link_to "友達を探す", user_search_path(current_user) %>
<%= link_to "ログアウトする", destroy_user_session_path, method: :delete %>

app/views/forms/_tag.html.erb
<% @emotion.tag_list.each do |tag| %>
  <%= link_to tag, tops_trend_path(tag_name: tag) %>
<% end %>

app/views/forms/_user.html.erb
<div class="demo-card-square mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title mdl-card--expand">
  <%= link_to user_top_path(@user) do %>
  <section>
  <% if @user.profile_image.present? %>
      <%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "100x100", class: "img" %>
  <% else %>
      <%= image_tag "no_image.jpg", format: 'jpeg', size: "100x100", class: "img" %>
  <% end %>
  </section>
  <section>
    <h1 class="mdl-card__title-text">
    <%= @user.name %>
    </h1>
    </section>
  <% end %>
  </div>
  <div class="mdl-card__supporting-text">
    <h3 class="mdl-card__title-text">
      <%= link_to user_follower_path(@user) do %>
      Follower数　<%=@user.followers.count %>　<br>
      <% end %>
      <%= link_to user_following_path(@user) do %>
      Folloing数　<%=@user.followings.count %>　<br>
      <% end %>
      <%= link_to user_favorites_path(@user) do %>
      Favorite数　<%=@user.favorites.count %><br>
      <% end %>
    </h3> 
  </div>
  <div class="mdl-card__actions mdl-card--border">
  <% if current_user.id != @user.id %>
      <% if @user.followed_by?(current_user) %>
          <p><%= link_to "フォロー解除", user_frendships_path(@user.id), method: :delete %></p>
      <% else %>
          <p><%= link_to "フォロー登録", user_frendships_path(@user.id), method: :post %></p></p>
      <% end %>    
  <% end %>
      <%= link_to "このユーザーについてもっとみる", user_path(@user) %>
      <%= link_to "チャットルーム", new_user_room_path %>
  </div>
</div>
   
      
  